#!/bin/bash

if [ $# -ne 3 ]; then
	echo "Usage: replaceSetting <filename> <key> <value>"
	echo "	Replaces setting if key exists, otherwise it appends the new key-value pair"
	exit 1
fi

filename=$1
key=$2
value=$3

grep -q "^${key}" $filename && sed -i "s/^${key}.*/${key}=${value}/" $filename || echo "${key}=${value}" >> $filename
